
import "./globals.css";
import type { Metadata } from "next";
import {Montserrat, Oxanium } from "next/font/google";

const oxanium = Oxanium({
weight: ['500','600'],
subsets:['latin'],
variable:'--font-oxanium',

});
const montserrat = Oxanium({
  weight: ['400','600'],
  subsets:['latin'],
  variable:'--font-montserrat',
  
  });


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="bg-black text-amber-300">
        {children}
  
      </body>
    </html>
  );
}
